(function () {
  window.GORO_DUNGEON_ITEM_CATALOG = [
    {
      key: "woodenSword",
      name: "木の棒",
      kind: "weapon",
      icon: "weapon",
      atk: 1,
      throwPower: 4,
      flavor: "そのへんで拾った棒きれ。ないよりはずっとよい。",
    },
    {
      key: "ironSword",
      name: "鉄の剣",
      kind: "weapon",
      icon: "weapon",
      atk: 3,
      throwPower: 6,
      flavor: "使い込まれているが、刃はまだ生きている。",
    },
    {
      key: "demonSlayer",
      name: "悪魔斬りの剣",
      kind: "weapon",
      icon: "weaponRare",
      atk: 2,
      throwPower: 7,
      slayer: { tag: "demon", label: "悪魔", bonus: 6 },
      flavor: "柄の紋様が、悪魔の気配に反応してかすかに熱を持つ。",
    },
    {
      key: "woodenShield",
      name: "木の盾",
      kind: "shield",
      icon: "shield",
      def: 1,
      throwPower: 3,
      flavor: "軽い。とっさに構えるぶんには十分。",
    },
    {
      key: "ironShield",
      name: "鉄の盾",
      kind: "shield",
      icon: "shield",
      def: 3,
      throwPower: 5,
      flavor: "重いが、殴られてもへこまない。",
    },
    {
      key: "riceBall",
      name: "おにぎり",
      kind: "food",
      icon: "food",
      hunger: 35,
      throwPower: 2,
      flavor: "にぎりたてではないが、腹はふくれる。",
    },
    {
      key: "bigRiceBall",
      name: "大きなおにぎり",
      kind: "food",
      icon: "food",
      hunger: 60,
      hungerMax: 5,
      throwPower: 3,
      flavor: "両手でやっと持てる大きさ。胃袋ごと広がる気がする。",
    },
    {
      key: "herb",
      name: "薬草",
      kind: "potion",
      icon: "potion",
      heal: 10,
      throwPower: 2,
      flavor: "噛むと苦い。傷にはよく効く。",
    },
    {
      key: "cureHerb",
      name: "なおし草",
      kind: "potion",
      icon: "potion",
      cureAll: true,
      throwPower: 2,
      flavor: "青い香りが鼻を抜ける。体の悪いものが薄れていく。",
    },
    {
      key: "enhanceScroll",
      name: "強化の巻物",
      kind: "scroll",
      icon: "scroll",
      effect: "enhance",
      description: "装備を1段階強化する",
      throwPower: 1,
      flavor: "読み上げると、手にした装備が小さく鳴る。",
    },
    {
      key: "thunderScroll",
      name: "いかずちの巻物",
      kind: "scroll",
      icon: "scroll",
      effect: "thunder",
      power: 8,
      description: "同じ部屋の敵に{power}ダメージ",
      throwPower: 1,
      flavor: "天井のないはずのない場所に、雷が落ちる。",
    },
    {
      key: "sleepWand",
      name: "眠りの杖",
      kind: "wand",
      icon: "wand",
      effect: "sleep",
      uses: 3,
      description: "直線上の敵1体を5ターン眠らせる",
      throwPower: 3,
      flavor: "先端の紫水晶を見ていると、まぶたが重くなる。",
    },
  ];
})();
