(function () {
  window.GORO_DUNGEON_MONSTER_CATALOG = [
    {
      key: "slime",
      name: "ぬるりスライム",
      defeatText: "吾郎はぬるぬるになった",
      stats: { baseHp: 5, baseAtk: 2, hpScale: 1, atkScale: 0.35, exp: 4 },
      asset: "assets/monster_slime.svg",
      draw: { offsetX: -23, offsetY: -42, w: 46, h: 40 },
      motion: {
        cycle: 720,
        bob: 1,
        scaleX: 1.08,
        scaleY: 0.9,
        anchor: 0.88,
        shadowX: 17,
        shadowY: 6,
        wobble: 0.055,
        hitScaleX: 1.18,
        hitScaleY: 0.82,
        hitRotation: 0.09,
        attackScaleX: 0.92,
        attackScaleY: 1.16,
        attackRotation: 0.07,
      },
      fallbackShape: {
        kind: "blob",
        fill: "#2dd4bf",
        shade: "rgba(20,184,166,0.65)",
        eye: "#0f172a",
      },
      burst: {
        kind: "particles",
        hitColor: "#2dd4bf",
        attackColor: "#5eead4",
        count: 5,
        size: 2.4,
        hitSpread: 18,
        attackSpread: 13,
      },
    },
    {
      key: "bat",
      name: "バサバサコウモリ",
      defeatText: "吾郎はバサバサになった",
      stats: { baseHp: 4, baseAtk: 3, hpScale: 0.8, atkScale: 0.45, exp: 5 },
      asset: "assets/monster_bat.svg",
      draw: { offsetX: -31, offsetY: -58, w: 62, h: 50 },
      motion: {
        cycle: 480,
        bob: 5,
        floatOffset: 2,
        scaleX: 1,
        scaleY: 1,
        anchor: 0.92,
        shadowX: 14,
        shadowY: 4,
        shadowOffsetY: 10,
        shadowBase: 0.86,
        shadowPulse: 0.08,
        wobble: 0.12,
        flapScaleX: 0.08,
        flapScaleY: -0.04,
        hitScaleX: 0.9,
        hitScaleY: 1.08,
        hitRotation: 0.09,
        attackScaleX: 1.08,
        attackScaleY: 0.94,
        attackRotation: 0.12,
      },
      fallbackShape: {
        kind: "winged",
        fill: "#8b5cf6",
        eye: "#111827",
      },
      burst: {
        kind: "arcs",
        hitColor: "#a78bfa",
        attackColor: "#ddd6fe",
        count: 2,
        size: 2,
        hitSpread: 14,
        attackSpread: 14,
      },
    },
    {
      key: "golem",
      name: "ゴロ岩ゴーレム",
      defeatText: "吾郎はゴロ岩につぶされてしまった",
      stats: { baseHp: 9, baseAtk: 4, hpScale: 1.4, atkScale: 0.6, exp: 9 },
      asset: "assets/monster_golem.svg",
      draw: { offsetX: -38, offsetY: -82, w: 76, h: 82 },
      motion: {
        cycle: 1120,
        bob: 0.5,
        scaleX: 1.014,
        scaleY: 0.994,
        anchor: 0.95,
        shadowX: 27,
        shadowY: 8,
        shadowBase: 1,
        shadowPulse: 0.035,
        wobble: 0.018,
        hitScaleX: 1.03,
        hitScaleY: 0.98,
        hitRotation: 0.035,
        attackScaleX: 1.035,
        attackScaleY: 1.02,
        attackRotation: 0.045,
      },
      fallbackShape: {
        kind: "block",
        fill: "#f59e0b",
        shade: "rgba(180,83,9,0.65)",
        eye: "#111827",
      },
      burst: {
        kind: "chunks",
        hitColor: "#b45309",
        attackColor: "#fbbf24",
        count: 6,
        size: 4,
        hitSpread: 16,
        attackSpread: 11,
      },
    },
  ];

  window.GORO_DUNGEON_ENEMY_SPAWN_TABLES = [
    { minFloor: 1, maxFloor: 1, count: [3, 4], entries: [{ type: "slime", weight: 100 }] },
    { minFloor: 2, maxFloor: 2, count: [4, 5], entries: [{ type: "slime", weight: 75 }, { type: "bat", weight: 25 }] },
    {
      minFloor: 3,
      maxFloor: 3,
      count: [4, 5],
      entries: [
        { type: "slime", weight: 50 },
        { type: "bat", weight: 40 },
        { type: "golem", weight: 10 },
      ],
    },
    {
      minFloor: 4,
      maxFloor: 4,
      count: [5, 6],
      entries: [
        { type: "slime", weight: 35 },
        { type: "bat", weight: 45 },
        { type: "golem", weight: 20 },
      ],
    },
    {
      minFloor: 5,
      maxFloor: 99,
      count: [5, 7],
      entries: [
        { type: "slime", weight: 20 },
        { type: "bat", weight: 45 },
        { type: "golem", weight: 35 },
      ],
    },
  ];
})();
